"""
Plotting helpers for visualising Rydberg-chain dynamics and correlations.

The functions in this module are intentionally simple and readable. Each one
creates a specific figure type that is commonly useful in small exact
simulations of driven Rydberg systems.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def _finalize_plot(save_path: str | Path | None = None) -> None:
    """
    Apply a tidy layout and optionally save the current figure.

    Parameters
    ----------
    save_path : str or pathlib.Path or None, optional
        File path where the current plot should be saved. If ``None``, the
        figure is not saved.
    """
    plt.tight_layout()
    if save_path is not None:
        Path(save_path).parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(save_path, dpi=300)


def plot_average_excitation(
    times: np.ndarray,
    avg_excitation: np.ndarray,
    N: int,
    title: str | None = None,
    save_path: str | Path | None = None,
) -> None:
    """
    Plot the average total excitation number <N_r(t)>.

    Physical interpretation
    -----------------------
    This plot shows how many atoms are excited on average as time evolves.
    Oscillatory behaviour reflects coherent quantum dynamics. Strong
    interactions can suppress the growth of excitations and are one signature
    of blockade physics.
    """
    plt.figure(figsize=(8, 5))
    plt.plot(times, avg_excitation, linewidth=2, label=r"$\langle N_r(t)\rangle$")
    plt.xlabel("Time")
    plt.ylabel("Average total excitation")
    plt.title(title or f"Average Excitation Dynamics (N = {N})")
    plt.legend()
    plt.grid(alpha=0.3)
    _finalize_plot(save_path)


def plot_site_resolved_heatmap(
    times: np.ndarray,
    site_probs: np.ndarray,
    title: str | None = None,
    save_path: str | Path | None = None,
) -> None:
    """
    Plot a heatmap of site-resolved excitation probability versus time.

    Physical interpretation
    -----------------------
    This plot shows how excitation probability is distributed in both space and
    time. It is especially useful for seeing whether edge sites and bulk sites
    behave differently, and for spotting spatial structure generated by
    interactions.
    """
    plt.figure(figsize=(8, 5))
    plt.imshow(
        site_probs.T,
        aspect="auto",
        origin="lower",
        extent=[times[0], times[-1], 0, site_probs.shape[1] - 1],
        cmap="viridis",
    )
    plt.colorbar(label="Excitation probability")
    plt.xlabel("Time")
    plt.ylabel("Site index")
    plt.title(title or "Site-Resolved Excitation Probability")
    _finalize_plot(save_path)


def plot_final_site_distribution(
    site_probs_final: np.ndarray,
    title: str | None = None,
    save_path: str | Path | None = None,
) -> None:
    """
    Plot the final-time site-resolved excitation probabilities.

    Physical interpretation
    -----------------------
    This bar-style view makes it easy to compare which sites are more or less
    excited at a chosen final time. In a finite chain with open boundaries,
    edge effects can make the profile non-uniform.
    """
    sites = np.arange(site_probs_final.size)
    plt.figure(figsize=(8, 5))
    plt.bar(sites, site_probs_final, color="tab:blue", alpha=0.85)
    plt.xlabel("Site index")
    plt.ylabel("Final excitation probability")
    plt.title(title or "Final-Time Site-Resolved Excitation")
    plt.ylim(0.0, 1.0)
    plt.grid(axis="y", alpha=0.3)
    _finalize_plot(save_path)


def plot_correlation_matrix(
    matrix: np.ndarray,
    title: str | None = None,
    save_path: str | Path | None = None,
) -> None:
    """
    Plot a correlation matrix as a heatmap.

    Physical interpretation
    -----------------------
    A matrix plot is a compact way to see how all site pairs are correlated at
    once. For example, strong suppression of nearby pair correlations can be a
    clear visual sign of the blockade regime.
    """
    plt.figure(figsize=(6, 5))
    plt.imshow(matrix, origin="lower", cmap="coolwarm")
    plt.colorbar(label="Correlation value")
    plt.xlabel("Site index j")
    plt.ylabel("Site index i")
    plt.title(title or "Correlation Matrix")
    _finalize_plot(save_path)


def compare_average_excitation(
    results_dict: dict,
    N: int,
    title: str | None = None,
    save_path: str | Path | None = None,
) -> None:
    """
    Compare average excitation dynamics across several simulation runs.

    Physical interpretation
    -----------------------
    This figure is useful for comparing physical regimes, such as weak and
    strong interactions. If blockade becomes important, the curves often show a
    reduced excitation build-up compared with the weakly interacting case.
    """
    plt.figure(figsize=(8, 5))

    for label, result in results_dict.items():
        plt.plot(
            result["times"],
            result["average_excitation"],
            linewidth=2,
            label=label,
        )

    plt.xlabel("Time")
    plt.ylabel("Average total excitation")
    plt.title(title or f"Comparison of Excitation Dynamics (N = {N})")
    plt.legend()
    plt.grid(alpha=0.3)
    _finalize_plot(save_path)
